name: Auto Update Subscription

on:
  schedule:
    - cron: '*/5 * * * *'  # اجرا هر 5 دقیقه
  workflow_dispatch:       # امکان اجرای دستی

jobs:
  update-subscription:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python main.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add subscription.txt config.yml
          git commit -m "🔄 Auto update subscription file" || echo "✅ No changes to commit"
          git push
